server:
  port: 8081

logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks